language: python

python:
  - "3.6"

sudo: required

install:
#  - pip install numpy numexpr scipy dask numba cython
#  - sudo apt-get update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  - conda install numpy numexpr scipy dask numba cython
  - conda create -y -n intel3 -c intel python=3 numpy numexpr scipy tbb dask numba cython
  # Install Intel APS
  - wget -O APS.tar.gz https://software.intel.com/sites/products/snapshots/application-snapshot/download-kits/APS_2018_update3_lin.tar.gz
  - mkdir APS
  - tar -xf ./APS.tar.gz -C ./APS --strip-components=1
  - source ./APS/apsvars.sh 
  - sudo sh -c 'echo 1 >/proc/sys/kernel/perf_event_paranoid'

script:
  - python bs_erf_numpy.py --steps 4
  - python bs_erf_numba_vec_par.py --steps 4
  - source activate intel3
  - python bs_erf_numpy.py --steps 4
  - aps python bs_erf_numba_vec_par.py --steps 4

